[project]
name = "dspy-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "dspy>=2.6.27",
    "mlflow>=3.1.1",
    "openai>=1.97.0",
]
